ARG baseImage=ubuntu:22.04x
FROM ${baseImage}

# Update repos and add kisak-mesa
RUN apt-get -y update 
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:kisak/kisak-mesa -y 
RUN apt-get -y update 

# Upgrade libraries and drivers
RUN apt-get -y upgrade

# Install mesa utilities
RUN apt-get -y install mesa-utils glmark2 libglu1-mesa

# For use in WSLg
ENV LD_LIBRARY_PATH="/usr/lib/wsl/lib"